<template>
  <div class="gemini-page">
    <section class="ai-hero">
      <span class="eyebrow">Your wellness companion</span>
      <h1>Ask the AI health assistant</h1>
      <p class="lede">
        Get around-the-clock answers on elder care, exercise, nutrition and everyday wellness.
        Always check with a doctor before making health decisions.
      </p>
    </section>

    <section class="ai-card">
      <!-- SUGGESTED PROMPTS -->
      <div v-if="!response && !isLoading" class="suggestions">
        <p class="suggestions-label">Try asking:</p>
        <div class="chip-row">
          <button v-for="s in suggestions" :key="s" class="chip" @click="useSuggestion(s)">
            {{ s }}
          </button>
        </div>
      </div>

      <!-- INPUT -->
      <div class="prompt-block">
        <label for="prompt" class="sr-only">Your question</label>
        <textarea
          id="prompt"
          v-model="userPrompt"
          placeholder="Ask me anything about your health, wellness or care…"
          rows="4"
          @keydown.enter.exact.prevent="getGeminiResponse"
        ></textarea>
        <div class="prompt-actions">
          <span class="hint"
            >Press <kbd>Enter</kbd> to send · <kbd>Shift + Enter</kbd> for a new line</span
          >
          <button
            @click="getGeminiResponse"
            class="btn-primary"
            :disabled="!userPrompt || isLoading"
          >
            {{ isLoading ? 'Thinking…' : 'Ask assistant' }}
          </button>
        </div>
      </div>

      <!-- LOADING -->
      <div v-if="isLoading" class="loading">
        <div class="dots"><span></span><span></span><span></span></div>
        <p>Composing a response…</p>
      </div>

      <!-- ERROR -->
      <div v-if="error" class="alert error">
        <strong>Couldn't reach the assistant</strong>
        <p>{{ error }}</p>
      </div>

      <!-- RESPONSE -->
      <article v-if="response && !isLoading" class="response">
        <div class="response-head">
          <div class="ai-badge" aria-hidden="true">AI</div>
          <span>Elder Care Connect Assistant</span>
        </div>
        <p class="response-text">{{ response }}</p>
        <p class="disclaimer">
          This response is generated by AI. Please verify important health information with a
          qualified professional.
        </p>
      </article>
    </section>
  </div>
</template>

<script>
import { ref } from 'vue'
import { useGemini } from '@/GeminiService'

export default {
  name: 'GeminiPrompt',
  setup() {
    const userPrompt = ref('')
    const response = ref('')
    const isLoading = ref(false)
    const error = ref(null)

    const suggestions = [
      'What exercises are good for seniors?',
      'How can I improve my memory?',
      'Which foods help lower blood pressure?',
      'Tips for better sleep as I age?'
    ]

    const useSuggestion = (s) => {
      userPrompt.value = s
    }

    const getGeminiResponse = async () => {
      if (!userPrompt.value.trim() || isLoading.value) return
      isLoading.value = true
      error.value = null
      response.value = ''
      try {
        response.value = await useGemini(userPrompt.value)
      } catch (err) {
        console.error('Error fetching Gemini response:', err)
        error.value = 'The assistant is unavailable right now. Please try again in a moment.'
      } finally {
        isLoading.value = false
      }
    }

    return {
      userPrompt,
      response,
      isLoading,
      error,
      suggestions,
      useSuggestion,
      getGeminiResponse
    }
  }
}
</script>

<style scoped>
@import url('https://fonts.googleapis.com/css2?family=Fraunces:opsz,wght@9..144,600&family=Source+Sans+3:wght@400;500;600;700&display=swap');

.gemini-page {
  --teal: #0f4c5c;
  --teal-deep: #0a3744;
  --coral: #e76f51;
  --sand: #fbf7f1;
  --line: #ece3d6;
  --muted: #5d6b73;
  --ink: #22333b;

  font-family: 'Source Sans 3', system-ui, sans-serif;
  color: var(--ink);
  background: var(--sand);
  margin: -1rem auto 0;
  padding: clamp(5rem, 9vw, 7rem) 1.25rem 3rem;
  max-width: 820px;
}

.sr-only {
  position: absolute;
  width: 1px;
  height: 1px;
  padding: 0;
  margin: -1px;
  overflow: hidden;
  clip: rect(0, 0, 0, 0);
  white-space: nowrap;
  border: 0;
}

.ai-hero {
  text-align: center;
  margin-bottom: 2rem;
}
.eyebrow {
  font-size: 0.8rem;
  letter-spacing: 0.14em;
  text-transform: uppercase;
  font-weight: 600;
  color: var(--coral);
}
.ai-hero h1 {
  font-family: 'Fraunces', Georgia, serif;
  font-weight: 600;
  font-size: clamp(1.9rem, 3.8vw, 2.6rem);
  color: var(--teal-deep);
  margin: 0.5rem 0 0.75rem;
  line-height: 1.15;
}
.lede {
  color: var(--muted);
  font-size: 1.1rem;
  line-height: 1.55;
  margin: 0;
  max-width: 60ch;
  margin-inline: auto;
}

.ai-card {
  background: #fff;
  border: 1px solid var(--line);
  border-radius: 22px;
  padding: clamp(1.5rem, 3vw, 2rem);
  box-shadow: 0 24px 60px -34px rgba(15, 76, 92, 0.4);
}

/* SUGGESTIONS */
.suggestions {
  margin-bottom: 1.5rem;
}
.suggestions-label {
  font-size: 0.85rem;
  letter-spacing: 0.06em;
  text-transform: uppercase;
  color: var(--muted);
  font-weight: 600;
  margin: 0 0 0.65rem;
}
.chip-row {
  display: flex;
  flex-wrap: wrap;
  gap: 0.5rem;
}
.chip {
  background: #fdf6ec;
  border: 1px solid var(--line);
  color: var(--teal-deep);
  border-radius: 999px;
  padding: 0.45rem 0.9rem;
  font-family: inherit;
  font-size: 0.9rem;
  font-weight: 500;
  cursor: pointer;
  transition:
    background 0.15s ease,
    border-color 0.15s ease;
}
.chip:hover {
  background: #fff;
  border-color: var(--teal);
}

/* PROMPT */
.prompt-block textarea {
  width: 100%;
  border: 1.5px solid var(--line);
  border-radius: 14px;
  padding: 1rem;
  font-family: inherit;
  font-size: 1rem;
  color: var(--ink);
  background: #fffdf9;
  resize: vertical;
  min-height: 100px;
  transition:
    border-color 0.15s ease,
    box-shadow 0.15s ease;
}
.prompt-block textarea:focus {
  outline: none;
  border-color: var(--teal);
  box-shadow: 0 0 0 3px rgba(15, 76, 92, 0.12);
}
.prompt-actions {
  display: flex;
  justify-content: space-between;
  align-items: center;
  gap: 1rem;
  flex-wrap: wrap;
  margin-top: 0.75rem;
}
.hint {
  color: var(--muted);
  font-size: 0.85rem;
}
.hint kbd {
  background: #f6efe2;
  padding: 0.1rem 0.4rem;
  border-radius: 4px;
  font-family: inherit;
  font-size: 0.8rem;
  color: var(--teal-deep);
}
.btn-primary {
  background: var(--coral);
  color: #fff;
  border: none;
  border-radius: 999px;
  padding: 0.7rem 1.6rem;
  font-weight: 600;
  font-size: 1rem;
  cursor: pointer;
  font-family: inherit;
  transition:
    transform 0.15s ease,
    opacity 0.15s ease;
}
.btn-primary:hover:not(:disabled) {
  transform: translateY(-2px);
}
.btn-primary:disabled {
  opacity: 0.5;
  cursor: not-allowed;
}

/* LOADING */
.loading {
  margin-top: 1.5rem;
  text-align: center;
  color: var(--muted);
}
.dots {
  display: inline-flex;
  gap: 5px;
  margin-bottom: 0.5rem;
}
.dots span {
  width: 8px;
  height: 8px;
  border-radius: 50%;
  background: var(--teal);
  animation: bounce 1.4s infinite ease-in-out both;
}
.dots span:nth-child(1) {
  animation-delay: -0.32s;
}
.dots span:nth-child(2) {
  animation-delay: -0.16s;
}
@keyframes bounce {
  0%,
  80%,
  100% {
    transform: scale(0);
    opacity: 0.5;
  }
  40% {
    transform: scale(1);
    opacity: 1;
  }
}

/* RESPONSE */
.response {
  margin-top: 1.75rem;
  background: #fdf6ec;
  border: 1px solid var(--line);
  border-radius: 16px;
  padding: 1.5rem;
}
.response-head {
  display: flex;
  align-items: center;
  gap: 0.6rem;
  margin-bottom: 0.85rem;
  font-weight: 600;
  color: var(--teal-deep);
  font-size: 0.95rem;
}
.ai-badge {
  width: 32px;
  height: 32px;
  border-radius: 8px;
  background: var(--teal);
  color: #fff;
  display: grid;
  place-items: center;
  font-size: 0.75rem;
  font-weight: 700;
}
.response-text {
  color: var(--ink);
  line-height: 1.7;
  margin: 0 0 1rem;
  white-space: pre-wrap;
}
.disclaimer {
  color: var(--muted);
  font-size: 0.85rem;
  font-style: italic;
  margin: 0;
  padding-top: 0.75rem;
  border-top: 1px solid var(--line);
}

/* ERROR */
.alert.error {
  margin-top: 1.5rem;
  background: #fdeee9;
  color: #b8472d;
  border-radius: 12px;
  padding: 0.85rem 1rem;
}
.alert.error strong {
  display: block;
  margin-bottom: 0.25rem;
}
.alert.error p {
  margin: 0;
  color: #96341f;
  font-size: 0.9rem;
}

@media (prefers-reduced-motion: reduce) {
  .btn-primary,
  .chip {
    transition: none;
  }
  .dots span {
    animation: none;
  }
}
</style>
